name: Call a different repo
on: workflow_dispatch
jobs:
   call_repo2:
      name: This will call a github workflow from diff branch
      runs-on: ubuntu-latest
      steps:
        - name: call github action 2
          run: |
            curl -X POST \
            -H "Accept: application/vnd.github+json" \
            https://github.com/rohansarkar1998/Github_Action.git/dispatches \
            -d '{"event_type":"trigger-from-repo1"}'
