name: this is called by GHA1
on:
   workflow_run:
      workflows: ["Github Action 01"]
      types:
         - completed
jobs:
   call_job:
           name: call the job
           runs-on: ubuntu-latest
           steps:
              - name: print hi
                run: echo "I am calling"
              
